const fs=require('fs'),vm=require('vm'),assert=require('assert');
const s=fs.readFileSync('Niji_Research_Helper.user.js','utf8');
assert(s.includes('// @version      1.0.46'));
assert(s.includes("const VERSION = '1.0.46';"));
assert(s.includes("const NRH_DB_NAME = 'NijiResearchHelperDB'"));
assert(s.includes("const CLOUD_STORES = ['videos','channels','wiki','pairs']"));
const start=s.indexOf('  function povAutomaticClues(source) {');
const end=s.indexOf('  function povNameMatches(',start);
assert(start>0&&end>start);
const ctx={channelName(v){return v.channel?.name||v.channel_name||'';},detectedEvents(){return [];}};
vm.createContext(ctx);
vm.runInContext(s.slice(start,end)+'\nthis.participants=povAutomaticClues;this.coaches=povCoachClues;',ctx);
const source={channel:{name:'レオス・ヴィンセント'},description:'参ります\n\nチーム\nレオス、ツルギくん、せつなさん、YASコーチ\n\n▼お借りした素敵なイラスト\nhttps://x.com/example'};
const people=ctx.participants(source),coaches=ctx.coaches(source);
assert(people.names.includes('ツルギ'),JSON.stringify(people));
assert(people.names.includes('せつな'),JSON.stringify(people));
assert(!people.names.some(n=>/YAS|コーチ/i.test(n)),JSON.stringify(people));
assert(coaches.names.includes('YAS'),JSON.stringify(coaches));
assert(!coaches.names.some(n=>/ツルギ|せつな|レオス/.test(n)),JSON.stringify(coaches));
const inline=ctx.coaches({channel:{name:'別人'},description:'チーム：甲、乙、YASコーチ'});
assert(inline.names.includes('YAS'),JSON.stringify(inline));
const classic=ctx.coaches({channel:{name:'別人'},description:'コーチ：YAS\n参加者：甲、乙'});
assert(classic.names.includes('YAS'),JSON.stringify(classic));
const unrelated=ctx.coaches({channel:{name:'別人'},description:'今日YASコーチに教わりました\n動画を見てください'});
assert(!unrelated.names.includes('YAS'),JSON.stringify(unrelated));
assert(s.includes("await boundedSearch({q:person},'コーチ名で再検索'"));
console.log('PASS roster participants (honorifics), inline YAS coach, classic heading, unrelated prose, coach fallback, version/schema');
