const fs=require('fs'),assert=require('assert'),vm=require('vm');
const s=fs.readFileSync('Niji_Research_Helper.user.js','utf8');
assert(s.includes('// @version      1.0.43'));
assert(s.includes("const VERSION = '1.0.43'"));
assert(s.includes("const NRH_DB_NAME = 'NijiResearchHelperDB'"));
assert(s.includes("const CLOUD_STORES = ['videos','channels','wiki','pairs']"));
assert(s.includes("forHandle:'@'+handle"),'resolve handle via channels.list');
assert(s.includes('await ytDetails([...new Set([...clues.videoIds,...missing])]'),'verify linked video using YouTube');
assert(s.includes("const manualHandle=input.match("),'manual channel URL supported');
assert(s.includes('既存・重複：'),'diagnostic counts');
assert(!s.includes('if(q)await ytSearch('),'global unanchored keyword auto-search removed');
const start=s.indexOf('  function povYoutubeVideo(item) {');
const end=s.indexOf('  function attachPovSupplement(',start);
assert(start>0&&end>start);
const ctx={URL,povYoutubeDuration(x){const m=String(x).match(/^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/);return m?Number(m[1]||0)*3600+Number(m[2]||0)*60+Number(m[3]||0):0;}};
vm.createContext(ctx);vm.runInContext(s.slice(start,end)+'\nthis.convert=povYoutubeVideo;',ctx);
const good=ctx.convert({id:'AAAAAAAAAAA',snippet:{title:'配信',channelId:'UC123'},contentDetails:{duration:'PT2H0M0S'},liveStreamingDetails:{actualStartTime:'2026-09-01T00:00:00Z',actualEndTime:'2026-09-01T02:00:00Z'}});
const clip=ctx.convert({id:'BBBBBBBBBBB',snippet:{title:'切り抜き'},contentDetails:{duration:'PT1M0S'}});
assert.strictEqual(good.povTimeVerified,true);
assert.strictEqual(clip.povTimeVerified,false);
const descStart=s.indexOf('  function povDescriptionClues(source) {');
const descEnd=s.indexOf('  function povYoutubeDuration(',descStart);
assert(descStart>0&&descEnd>descStart);
vm.runInContext('function channelId(v){return v.channel?.id||v.channel_id||"";}function parseVideoIdFromUrl(s){return s.match(/[?&]v=([A-Za-z0-9_-]{11})/)?.[1]||null;}\n'+s.slice(descStart,descEnd)+'\nthis.clues=povDescriptionClues;',ctx);
const clues=ctx.clues({id:'XXXXXXXXXXX',channel:{id:'UC0123456789012345678901'},description:'参加者 https://www.youtube.com/@ExampleCreator 配信 https://www.youtube.com/watch?v=YYYYYYYYYYY'});
assert(clues.handles.includes('ExampleCreator'));
assert(clues.videoIds.includes('YYYYYYYYYYY'));
console.log('PASS: version/schema, handles, direct-video recheck, bounded search, livestream+clip fixtures, description clues');