const fs=require('fs'),assert=require('assert'),vm=require('vm');
const s=fs.readFileSync('Niji_Research_Helper.user.js','utf8');
assert(s.includes('// @version      1.0.45'));
assert(s.includes("const VERSION = '1.0.45'"));
assert(s.includes("const NRH_DB_NAME = 'NijiResearchHelperDB'"));
assert(s.includes("const CLOUD_STORES = ['videos','channels','wiki','pairs']"));
assert(s.includes('trustedCoachIds=new Set(coachLinks.channelIds)'));
assert(s.includes("'概要欄のコーチ名から自動検索'"));
assert(s.includes("'🎓 コーチの関連配信（時間重複なし・要確認）'"));
assert(s.includes('coach.names.length'));
assert(s.includes('if(searches>=8)return;'));
const a=s.indexOf('  function povCoachClues(source) {');
const b=s.indexOf('  function povNameMatches(channel,person) {',a);
assert(a>=0&&b>a);
const ctx={channelName:()=> '不破湊'};vm.createContext(ctx);
vm.runInContext(s.slice(a,b)+'\nthis.coachClues=povCoachClues;',ctx);
let result=ctx.coachClues({description:'参加者：小柳ロウ\nコーチ：ハセシン、nqrse\n企画：大会',channel:{name:'不破湊'}});
assert(result.names.includes('ハセシン'));
assert(result.names.includes('nqrse'));
assert(!result.names.includes('小柳ロウ'));
result=ctx.coachClues({description:'コーチ\n・渋谷ハル https://www.youtube.com/@ShibuyaHAL\n・天月\n参加者：葛葉',channel:{name:'不破湊'}});
assert(result.names.some(n=>n.includes('渋谷ハル')));
assert(result.names.includes('天月'));
assert(result.handles.includes('ShibuyaHAL'));
assert(!result.names.includes('葛葉'));
result=ctx.coachClues({description:'コーチングを受ける配信\n参加者：小柳ロウ',channel:{name:'不破湊'}});
assert.strictEqual(result.names.length,0);
console.log('PASS: coach labels, multi-coach names, URL handles, unrelated names excluded; DB/cloud constants unchanged');
