const fs=require('fs'),vm=require('vm'),assert=require('assert');
const s=fs.readFileSync('Niji_Research_Helper.user.js','utf8');
assert(s.includes('// @version      1.0.44'));
assert(s.includes("const VERSION = '1.0.44'"));
assert(s.includes("const NRH_DB_NAME = 'NijiResearchHelperDB'"));
assert(s.includes("const CLOUD_STORES = ['videos','channels','wiki','pairs']"));
assert(s.includes("const KEY_YT_API = 'npf_youtube_api_key_local_v1'"));
assert(s.includes('await gmSet(KEY_YT_API,enteredKey)'));
assert(s.includes("await gmGet(KEY_YT_API,''"));
assert(!s.includes('channelInput.value.trim()'),'manual channel entry must not be required');
assert(s.includes("q:[person,event].filter(Boolean).join(' ')"),'participant/event combined searches');
assert(s.includes("q:person"),'fallback participant-only search');
assert(s.includes("q:[event,game].filter(Boolean).join(' ')"),'event-wide search');
assert(s.includes("if(searches>=6)return"),'quota-aware search cap');
assert(s.includes("eventType:'completed'"),'completed livestream search');
assert(s.includes("if(!direct&&!trusted&&!named&&!eventLead)return reject()"),'reject unrelated search hits');
const a=s.indexOf('  function povAutomaticClues(source) {');
const b=s.indexOf('  function povYoutubeDuration(s) {',a);
assert(a>0&&b>a);
const ctx={channelName:x=>x.channel?.name||'',detectedEvents:t=>/V最協/.test(t)?['V最協']:[]};
vm.createContext(ctx);vm.runInContext(s.slice(a,b)+'\nthis.clues=povAutomaticClues;this.nameMatch=povNameMatches;this.eventMatch=povEventMatches;',ctx);
const sample={title:'【V最協第二幕】ストリートファイター6 本戦',channel:{name:'配信者本人'},description:'参加者：レオス・ヴィンセント、斜落せつな\n企画 #V最協第二幕\n関連 https://youtube.com/watch?v=ABCDEFGHIJK'};
const out=ctx.clues(sample);
assert(out.names.includes('レオス・ヴィンセント'),'extract Japanese names preserving middle dot');
assert(out.names.includes('斜落せつな'),'extract second participant');
assert(out.events.some(x=>x.includes('V最協')),'extract event');
assert(ctx.nameMatch('レオス・ヴィンセント / Leos.Vincent 【にじさんじ】','レオス・ヴィンセント'),'recognize participant channel');
assert(!ctx.nameMatch('無関係の配信者','レオス・ヴィンセント'),'reject unrelated channel');
assert(ctx.eventMatch({title:'【V最協第二幕】別視点'},'#V最協第二幕'),'event verification');
assert(!ctx.eventMatch({title:'ストリートファイター6 遊ぶ'},'#V最協第二幕'),'generic game is not event');
const unlabeled=ctx.clues({title:'ゲーム配信',channel:{name:'本人'},description:'今日はゲームをやります\nチャンネル登録よろしく'});
assert.strictEqual(unlabeled.names.length,0,'do not treat arbitrary description prose as names');
console.log('PASS automatic POV: participant names, event clues, candidate relevance, no mandatory URL, saved key, search cap, DB/schema invariance');